apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-docker-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-docker-k8s
  template:
    metadata:
      labels:
        app: autoscale-docker-k8s
    spec:
      containers:
      - name: autoscale-docker-k8s
        image:  adityajethwa7/autoscale-docker-k8s:latest
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
